version: "3.9"
services:
  db:
    build: ./backend/db
    ports:
      - "5432:5432"
    networks:
      - ita
    environment:
        POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 10


  users:
    build: ./backend/users
    ports:
      - "8080:8080"
    networks:
      - ita
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/users/test" ]
      interval: 10s
      timeout: 5s
      retries: 5

  properties:
    build: ./backend/properties
    ports:
      - "8081:8081"
    networks:
      - ita
    depends_on:
      - db

  search:
    image: searchms:latest
    ports:
      - "8082:8082"
    networks:
      - ita
    depends_on:
      db:
        condition: service_healthy


  gateway:
    build: ./backend/gateway
    ports:
      - "5000:5000"
    networks:
      - ita
    depends_on:
      - db
      - users
      - properties
      - search

networks:
  ita:
    name: ita
    driver: bridge