version: "3.9"
services:
  db:
    build: ./backend/usersdb
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres

  users:
    build: ./backend/users
    ports:
      - "8080:8080"
    depends_on:
      - db

  propertiesdb:
    build: ./backend/propertiesdb
    ports:
      - "5433:5433"
    environment:
        POSTGRES_USER: postgres

  properties:
    build: ./backend/properties
    ports:
      - "8081:8081"
    depends_on:
      - propertiesdb