\c postgres;

DROP DATABASE ita;

CREATE DATABASE ita;

\c ita;

CREATE TABLE users (
                       id bigserial primary key,
                       email      varchar(255),
                       first_name varchar(255),
                       last_name  varchar(255),
                       password   varchar(255)
);

INSERT INTO users (email, first_name, last_name, password) VALUES ('nik.kovacevic.5@gmail.com', 'Nik', 'Kovacevic', '$2a$10$0j8HZ9C1hnaZ1MQhkWJ69ug4fMMCMAKyIoB/rj2H1S0jIF8725wLi');

CREATE TABLE properties (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            link VARCHAR(255),
                            title VARCHAR(255),
                            location VARCHAR(255),
                            price VARCHAR(255),
                            image VARCHAR(255),
                            CONSTRAINT pk_properties PRIMARY KEY (id)
);

COPY properties (link, title, location, price, image) FROM '/data.csv' DELIMITER ',' CSV;