\c postgres;

DROP DATABASE properties;

CREATE DATABASE properties;

\c properties;

CREATE TABLE properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    link VARCHAR(255),
    title VARCHAR(255),
    location VARCHAR(255),
    price VARCHAR(255),
    image VARCHAR(255),
    CONSTRAINT pk_properties PRIMARY KEY (id)
);

COPY properties (link, title, location, price, image) FROM '/data.csv' DELIMITER ',' CSV;