// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: property.proto

//package ita.ms.grpc;

// to je generiralo v target/generated-sources/protobuf/java/ita/ms/grpc/PropertyOuterClass.java

public final class PropertyOuterClassCopy {
    private PropertyOuterClassCopy() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface PropertyOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ita.ms.Property)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string title = 1;</code>
         * @return The title.
         */
        java.lang.String getTitle();
        /**
         * <code>string title = 1;</code>
         * @return The bytes for title.
         */
        com.google.protobuf.ByteString
        getTitleBytes();

        /**
         * <code>string location = 2;</code>
         * @return The location.
         */
        java.lang.String getLocation();
        /**
         * <code>string location = 2;</code>
         * @return The bytes for location.
         */
        com.google.protobuf.ByteString
        getLocationBytes();

        /**
         * <code>string link = 3;</code>
         * @return The link.
         */
        java.lang.String getLink();
        /**
         * <code>string link = 3;</code>
         * @return The bytes for link.
         */
        com.google.protobuf.ByteString
        getLinkBytes();

        /**
         * <code>string price = 4;</code>
         * @return The price.
         */
        java.lang.String getPrice();
        /**
         * <code>string price = 4;</code>
         * @return The bytes for price.
         */
        com.google.protobuf.ByteString
        getPriceBytes();

        /**
         * <code>string image = 5;</code>
         * @return The image.
         */
        java.lang.String getImage();
        /**
         * <code>string image = 5;</code>
         * @return The bytes for image.
         */
        com.google.protobuf.ByteString
        getImageBytes();
    }
    /**
     * Protobuf type {@code ita.ms.Property}
     */
    public static final class Property extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ita.ms.Property)
            PropertyOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Property.newBuilder() to construct.
        private Property(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Property() {
            title_ = "";
            location_ = "";
            link_ = "";
            price_ = "";
            image_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Property();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Property(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            title_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            location_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            link_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            price_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            image_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ita.ms.PropertyOuterClass.internal_static_ita_ms_Property_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ita.ms.PropertyOuterClass.internal_static_ita_ms_Property_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ita.ms.PropertyOuterClass.Property.class, ita.ms.PropertyOuterClass.Property.Builder.class);
        }

        public static final int TITLE_FIELD_NUMBER = 1;
        private volatile java.lang.Object title_;
        /**
         * <code>string title = 1;</code>
         * @return The title.
         */
        @java.lang.Override
        public java.lang.String getTitle() {
            java.lang.Object ref = title_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                title_ = s;
                return s;
            }
        }
        /**
         * <code>string title = 1;</code>
         * @return The bytes for title.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getTitleBytes() {
            java.lang.Object ref = title_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                title_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int LOCATION_FIELD_NUMBER = 2;
        private volatile java.lang.Object location_;
        /**
         * <code>string location = 2;</code>
         * @return The location.
         */
        @java.lang.Override
        public java.lang.String getLocation() {
            java.lang.Object ref = location_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                location_ = s;
                return s;
            }
        }
        /**
         * <code>string location = 2;</code>
         * @return The bytes for location.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getLocationBytes() {
            java.lang.Object ref = location_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                location_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int LINK_FIELD_NUMBER = 3;
        private volatile java.lang.Object link_;
        /**
         * <code>string link = 3;</code>
         * @return The link.
         */
        @java.lang.Override
        public java.lang.String getLink() {
            java.lang.Object ref = link_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                link_ = s;
                return s;
            }
        }
        /**
         * <code>string link = 3;</code>
         * @return The bytes for link.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getLinkBytes() {
            java.lang.Object ref = link_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                link_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PRICE_FIELD_NUMBER = 4;
        private volatile java.lang.Object price_;
        /**
         * <code>string price = 4;</code>
         * @return The price.
         */
        @java.lang.Override
        public java.lang.String getPrice() {
            java.lang.Object ref = price_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                price_ = s;
                return s;
            }
        }
        /**
         * <code>string price = 4;</code>
         * @return The bytes for price.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getPriceBytes() {
            java.lang.Object ref = price_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                price_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int IMAGE_FIELD_NUMBER = 5;
        private volatile java.lang.Object image_;
        /**
         * <code>string image = 5;</code>
         * @return The image.
         */
        @java.lang.Override
        public java.lang.String getImage() {
            java.lang.Object ref = image_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                image_ = s;
                return s;
            }
        }
        /**
         * <code>string image = 5;</code>
         * @return The bytes for image.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getImageBytes() {
            java.lang.Object ref = image_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                image_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getTitleBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
            }
            if (!getLocationBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, location_);
            }
            if (!getLinkBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, link_);
            }
            if (!getPriceBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, price_);
            }
            if (!getImageBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, image_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getTitleBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
            }
            if (!getLocationBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, location_);
            }
            if (!getLinkBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, link_);
            }
            if (!getPriceBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, price_);
            }
            if (!getImageBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, image_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ita.ms.PropertyOuterClass.Property)) {
                return super.equals(obj);
            }
            ita.ms.PropertyOuterClass.Property other = (ita.ms.PropertyOuterClass.Property) obj;

            if (!getTitle()
                    .equals(other.getTitle())) return false;
            if (!getLocation()
                    .equals(other.getLocation())) return false;
            if (!getLink()
                    .equals(other.getLink())) return false;
            if (!getPrice()
                    .equals(other.getPrice())) return false;
            if (!getImage()
                    .equals(other.getImage())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TITLE_FIELD_NUMBER;
            hash = (53 * hash) + getTitle().hashCode();
            hash = (37 * hash) + LOCATION_FIELD_NUMBER;
            hash = (53 * hash) + getLocation().hashCode();
            hash = (37 * hash) + LINK_FIELD_NUMBER;
            hash = (53 * hash) + getLink().hashCode();
            hash = (37 * hash) + PRICE_FIELD_NUMBER;
            hash = (53 * hash) + getPrice().hashCode();
            hash = (37 * hash) + IMAGE_FIELD_NUMBER;
            hash = (53 * hash) + getImage().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static ita.ms.PropertyOuterClass.Property parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static ita.ms.PropertyOuterClass.Property parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static ita.ms.PropertyOuterClass.Property parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static ita.ms.PropertyOuterClass.Property parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static ita.ms.PropertyOuterClass.Property parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static ita.ms.PropertyOuterClass.Property parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static ita.ms.PropertyOuterClass.Property parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static ita.ms.PropertyOuterClass.Property parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static ita.ms.PropertyOuterClass.Property parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static ita.ms.PropertyOuterClass.Property parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static ita.ms.PropertyOuterClass.Property parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static ita.ms.PropertyOuterClass.Property parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(ita.ms.PropertyOuterClass.Property prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code ita.ms.Property}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ita.ms.Property)
                ita.ms.PropertyOuterClass.PropertyOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ita.ms.PropertyOuterClass.internal_static_ita_ms_Property_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ita.ms.PropertyOuterClass.internal_static_ita_ms_Property_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ita.ms.PropertyOuterClass.Property.class, ita.ms.PropertyOuterClass.Property.Builder.class);
            }

            // Construct using ita.ms.PropertyOuterClass.Property.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                title_ = "";

                location_ = "";

                link_ = "";

                price_ = "";

                image_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ita.ms.PropertyOuterClass.internal_static_ita_ms_Property_descriptor;
            }

            @java.lang.Override
            public ita.ms.PropertyOuterClass.Property getDefaultInstanceForType() {
                return ita.ms.PropertyOuterClass.Property.getDefaultInstance();
            }

            @java.lang.Override
            public ita.ms.PropertyOuterClass.Property build() {
                ita.ms.PropertyOuterClass.Property result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public ita.ms.PropertyOuterClass.Property buildPartial() {
                ita.ms.PropertyOuterClass.Property result = new ita.ms.PropertyOuterClass.Property(this);
                result.title_ = title_;
                result.location_ = location_;
                result.link_ = link_;
                result.price_ = price_;
                result.image_ = image_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ita.ms.PropertyOuterClass.Property) {
                    return mergeFrom((ita.ms.PropertyOuterClass.Property)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ita.ms.PropertyOuterClass.Property other) {
                if (other == ita.ms.PropertyOuterClass.Property.getDefaultInstance()) return this;
                if (!other.getTitle().isEmpty()) {
                    title_ = other.title_;
                    onChanged();
                }
                if (!other.getLocation().isEmpty()) {
                    location_ = other.location_;
                    onChanged();
                }
                if (!other.getLink().isEmpty()) {
                    link_ = other.link_;
                    onChanged();
                }
                if (!other.getPrice().isEmpty()) {
                    price_ = other.price_;
                    onChanged();
                }
                if (!other.getImage().isEmpty()) {
                    image_ = other.image_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ita.ms.PropertyOuterClass.Property parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ita.ms.PropertyOuterClass.Property) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object title_ = "";
            /**
             * <code>string title = 1;</code>
             * @return The title.
             */
            public java.lang.String getTitle() {
                java.lang.Object ref = title_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    title_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string title = 1;</code>
             * @return The bytes for title.
             */
            public com.google.protobuf.ByteString
            getTitleBytes() {
                java.lang.Object ref = title_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    title_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string title = 1;</code>
             * @param value The title to set.
             * @return This builder for chaining.
             */
            public Builder setTitle(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                title_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string title = 1;</code>
             * @return This builder for chaining.
             */
            public Builder clearTitle() {

                title_ = getDefaultInstance().getTitle();
                onChanged();
                return this;
            }
            /**
             * <code>string title = 1;</code>
             * @param value The bytes for title to set.
             * @return This builder for chaining.
             */
            public Builder setTitleBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                title_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object location_ = "";
            /**
             * <code>string location = 2;</code>
             * @return The location.
             */
            public java.lang.String getLocation() {
                java.lang.Object ref = location_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    location_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string location = 2;</code>
             * @return The bytes for location.
             */
            public com.google.protobuf.ByteString
            getLocationBytes() {
                java.lang.Object ref = location_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    location_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string location = 2;</code>
             * @param value The location to set.
             * @return This builder for chaining.
             */
            public Builder setLocation(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                location_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string location = 2;</code>
             * @return This builder for chaining.
             */
            public Builder clearLocation() {

                location_ = getDefaultInstance().getLocation();
                onChanged();
                return this;
            }
            /**
             * <code>string location = 2;</code>
             * @param value The bytes for location to set.
             * @return This builder for chaining.
             */
            public Builder setLocationBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                location_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object link_ = "";
            /**
             * <code>string link = 3;</code>
             * @return The link.
             */
            public java.lang.String getLink() {
                java.lang.Object ref = link_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    link_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string link = 3;</code>
             * @return The bytes for link.
             */
            public com.google.protobuf.ByteString
            getLinkBytes() {
                java.lang.Object ref = link_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    link_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string link = 3;</code>
             * @param value The link to set.
             * @return This builder for chaining.
             */
            public Builder setLink(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                link_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string link = 3;</code>
             * @return This builder for chaining.
             */
            public Builder clearLink() {

                link_ = getDefaultInstance().getLink();
                onChanged();
                return this;
            }
            /**
             * <code>string link = 3;</code>
             * @param value The bytes for link to set.
             * @return This builder for chaining.
             */
            public Builder setLinkBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                link_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object price_ = "";
            /**
             * <code>string price = 4;</code>
             * @return The price.
             */
            public java.lang.String getPrice() {
                java.lang.Object ref = price_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    price_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string price = 4;</code>
             * @return The bytes for price.
             */
            public com.google.protobuf.ByteString
            getPriceBytes() {
                java.lang.Object ref = price_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    price_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string price = 4;</code>
             * @param value The price to set.
             * @return This builder for chaining.
             */
            public Builder setPrice(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                price_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string price = 4;</code>
             * @return This builder for chaining.
             */
            public Builder clearPrice() {

                price_ = getDefaultInstance().getPrice();
                onChanged();
                return this;
            }
            /**
             * <code>string price = 4;</code>
             * @param value The bytes for price to set.
             * @return This builder for chaining.
             */
            public Builder setPriceBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                price_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object image_ = "";
            /**
             * <code>string image = 5;</code>
             * @return The image.
             */
            public java.lang.String getImage() {
                java.lang.Object ref = image_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    image_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string image = 5;</code>
             * @return The bytes for image.
             */
            public com.google.protobuf.ByteString
            getImageBytes() {
                java.lang.Object ref = image_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    image_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string image = 5;</code>
             * @param value The image to set.
             * @return This builder for chaining.
             */
            public Builder setImage(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                image_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string image = 5;</code>
             * @return This builder for chaining.
             */
            public Builder clearImage() {

                image_ = getDefaultInstance().getImage();
                onChanged();
                return this;
            }
            /**
             * <code>string image = 5;</code>
             * @param value The bytes for image to set.
             * @return This builder for chaining.
             */
            public Builder setImageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                image_ = value;
                onChanged();
                return this;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ita.ms.Property)
        }

        // @@protoc_insertion_point(class_scope:ita.ms.Property)
        private static final ita.ms.PropertyOuterClass.Property DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new ita.ms.PropertyOuterClass.Property();
        }

        public static ita.ms.PropertyOuterClass.Property getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Property>
                PARSER = new com.google.protobuf.AbstractParser<Property>() {
            @java.lang.Override
            public Property parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Property(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Property> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Property> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public ita.ms.PropertyOuterClass.Property getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface PropertyListOrBuilder extends
            // @@protoc_insertion_point(interface_extends:ita.ms.PropertyList)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .ita.ms.Property properties = 1;</code>
         */
        java.util.List<ita.ms.PropertyOuterClass.Property>
        getPropertiesList();
        /**
         * <code>repeated .ita.ms.Property properties = 1;</code>
         */
        ita.ms.PropertyOuterClass.Property getProperties(int index);
        /**
         * <code>repeated .ita.ms.Property properties = 1;</code>
         */
        int getPropertiesCount();
        /**
         * <code>repeated .ita.ms.Property properties = 1;</code>
         */
        java.util.List<? extends ita.ms.PropertyOuterClass.PropertyOrBuilder>
        getPropertiesOrBuilderList();
        /**
         * <code>repeated .ita.ms.Property properties = 1;</code>
         */
        ita.ms.PropertyOuterClass.PropertyOrBuilder getPropertiesOrBuilder(
                int index);
    }
    /**
     * Protobuf type {@code ita.ms.PropertyList}
     */
    public static final class PropertyList extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:ita.ms.PropertyList)
            PropertyListOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use PropertyList.newBuilder() to construct.
        private PropertyList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private PropertyList() {
            properties_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new PropertyList();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private PropertyList(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                properties_ = new java.util.ArrayList<ita.ms.PropertyOuterClass.Property>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            properties_.add(
                                    input.readMessage(ita.ms.PropertyOuterClass.Property.parser(), extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    properties_ = java.util.Collections.unmodifiableList(properties_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ita.ms.PropertyOuterClass.internal_static_ita_ms_PropertyList_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ita.ms.PropertyOuterClass.internal_static_ita_ms_PropertyList_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ita.ms.PropertyOuterClass.PropertyList.class, ita.ms.PropertyOuterClass.PropertyList.Builder.class);
        }

        public static final int PROPERTIES_FIELD_NUMBER = 1;
        private java.util.List<ita.ms.PropertyOuterClass.Property> properties_;
        /**
         * <code>repeated .ita.ms.Property properties = 1;</code>
         */
        @java.lang.Override
        public java.util.List<ita.ms.PropertyOuterClass.Property> getPropertiesList() {
            return properties_;
        }
        /**
         * <code>repeated .ita.ms.Property properties = 1;</code>
         */
        @java.lang.Override
        public java.util.List<? extends ita.ms.PropertyOuterClass.PropertyOrBuilder>
        getPropertiesOrBuilderList() {
            return properties_;
        }
        /**
         * <code>repeated .ita.ms.Property properties = 1;</code>
         */
        @java.lang.Override
        public int getPropertiesCount() {
            return properties_.size();
        }
        /**
         * <code>repeated .ita.ms.Property properties = 1;</code>
         */
        @java.lang.Override
        public ita.ms.PropertyOuterClass.Property getProperties(int index) {
            return properties_.get(index);
        }
        /**
         * <code>repeated .ita.ms.Property properties = 1;</code>
         */
        @java.lang.Override
        public ita.ms.PropertyOuterClass.PropertyOrBuilder getPropertiesOrBuilder(
                int index) {
            return properties_.get(index);
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < properties_.size(); i++) {
                output.writeMessage(1, properties_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < properties_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, properties_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ita.ms.PropertyOuterClass.PropertyList)) {
                return super.equals(obj);
            }
            ita.ms.PropertyOuterClass.PropertyList other = (ita.ms.PropertyOuterClass.PropertyList) obj;

            if (!getPropertiesList()
                    .equals(other.getPropertiesList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getPropertiesCount() > 0) {
                hash = (37 * hash) + PROPERTIES_FIELD_NUMBER;
                hash = (53 * hash) + getPropertiesList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static ita.ms.PropertyOuterClass.PropertyList parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static ita.ms.PropertyOuterClass.PropertyList parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static ita.ms.PropertyOuterClass.PropertyList parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static ita.ms.PropertyOuterClass.PropertyList parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static ita.ms.PropertyOuterClass.PropertyList parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static ita.ms.PropertyOuterClass.PropertyList parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static ita.ms.PropertyOuterClass.PropertyList parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static ita.ms.PropertyOuterClass.PropertyList parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static ita.ms.PropertyOuterClass.PropertyList parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static ita.ms.PropertyOuterClass.PropertyList parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static ita.ms.PropertyOuterClass.PropertyList parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static ita.ms.PropertyOuterClass.PropertyList parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(ita.ms.PropertyOuterClass.PropertyList prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code ita.ms.PropertyList}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:ita.ms.PropertyList)
                ita.ms.PropertyOuterClass.PropertyListOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ita.ms.PropertyOuterClass.internal_static_ita_ms_PropertyList_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ita.ms.PropertyOuterClass.internal_static_ita_ms_PropertyList_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ita.ms.PropertyOuterClass.PropertyList.class, ita.ms.PropertyOuterClass.PropertyList.Builder.class);
            }

            // Construct using ita.ms.PropertyOuterClass.PropertyList.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getPropertiesFieldBuilder();
                }
            }
            @java.lang.Override
            public Builder clear() {
                super.clear();
                if (propertiesBuilder_ == null) {
                    properties_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    propertiesBuilder_.clear();
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ita.ms.PropertyOuterClass.internal_static_ita_ms_PropertyList_descriptor;
            }

            @java.lang.Override
            public ita.ms.PropertyOuterClass.PropertyList getDefaultInstanceForType() {
                return ita.ms.PropertyOuterClass.PropertyList.getDefaultInstance();
            }

            @java.lang.Override
            public ita.ms.PropertyOuterClass.PropertyList build() {
                ita.ms.PropertyOuterClass.PropertyList result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public ita.ms.PropertyOuterClass.PropertyList buildPartial() {
                ita.ms.PropertyOuterClass.PropertyList result = new ita.ms.PropertyOuterClass.PropertyList(this);
                int from_bitField0_ = bitField0_;
                if (propertiesBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)) {
                        properties_ = java.util.Collections.unmodifiableList(properties_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.properties_ = properties_;
                } else {
                    result.properties_ = propertiesBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }
            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }
            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }
            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }
            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }
            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }
            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ita.ms.PropertyOuterClass.PropertyList) {
                    return mergeFrom((ita.ms.PropertyOuterClass.PropertyList)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ita.ms.PropertyOuterClass.PropertyList other) {
                if (other == ita.ms.PropertyOuterClass.PropertyList.getDefaultInstance()) return this;
                if (propertiesBuilder_ == null) {
                    if (!other.properties_.isEmpty()) {
                        if (properties_.isEmpty()) {
                            properties_ = other.properties_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensurePropertiesIsMutable();
                            properties_.addAll(other.properties_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.properties_.isEmpty()) {
                        if (propertiesBuilder_.isEmpty()) {
                            propertiesBuilder_.dispose();
                            propertiesBuilder_ = null;
                            properties_ = other.properties_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            propertiesBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getPropertiesFieldBuilder() : null;
                        } else {
                            propertiesBuilder_.addAllMessages(other.properties_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ita.ms.PropertyOuterClass.PropertyList parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ita.ms.PropertyOuterClass.PropertyList) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.util.List<ita.ms.PropertyOuterClass.Property> properties_ =
                    java.util.Collections.emptyList();
            private void ensurePropertiesIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    properties_ = new java.util.ArrayList<ita.ms.PropertyOuterClass.Property>(properties_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    ita.ms.PropertyOuterClass.Property, ita.ms.PropertyOuterClass.Property.Builder, ita.ms.PropertyOuterClass.PropertyOrBuilder> propertiesBuilder_;

            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public java.util.List<ita.ms.PropertyOuterClass.Property> getPropertiesList() {
                if (propertiesBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(properties_);
                } else {
                    return propertiesBuilder_.getMessageList();
                }
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public int getPropertiesCount() {
                if (propertiesBuilder_ == null) {
                    return properties_.size();
                } else {
                    return propertiesBuilder_.getCount();
                }
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public ita.ms.PropertyOuterClass.Property getProperties(int index) {
                if (propertiesBuilder_ == null) {
                    return properties_.get(index);
                } else {
                    return propertiesBuilder_.getMessage(index);
                }
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public Builder setProperties(
                    int index, ita.ms.PropertyOuterClass.Property value) {
                if (propertiesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePropertiesIsMutable();
                    properties_.set(index, value);
                    onChanged();
                } else {
                    propertiesBuilder_.setMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public Builder setProperties(
                    int index, ita.ms.PropertyOuterClass.Property.Builder builderForValue) {
                if (propertiesBuilder_ == null) {
                    ensurePropertiesIsMutable();
                    properties_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    propertiesBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public Builder addProperties(ita.ms.PropertyOuterClass.Property value) {
                if (propertiesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePropertiesIsMutable();
                    properties_.add(value);
                    onChanged();
                } else {
                    propertiesBuilder_.addMessage(value);
                }
                return this;
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public Builder addProperties(
                    int index, ita.ms.PropertyOuterClass.Property value) {
                if (propertiesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensurePropertiesIsMutable();
                    properties_.add(index, value);
                    onChanged();
                } else {
                    propertiesBuilder_.addMessage(index, value);
                }
                return this;
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public Builder addProperties(
                    ita.ms.PropertyOuterClass.Property.Builder builderForValue) {
                if (propertiesBuilder_ == null) {
                    ensurePropertiesIsMutable();
                    properties_.add(builderForValue.build());
                    onChanged();
                } else {
                    propertiesBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public Builder addProperties(
                    int index, ita.ms.PropertyOuterClass.Property.Builder builderForValue) {
                if (propertiesBuilder_ == null) {
                    ensurePropertiesIsMutable();
                    properties_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    propertiesBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public Builder addAllProperties(
                    java.lang.Iterable<? extends ita.ms.PropertyOuterClass.Property> values) {
                if (propertiesBuilder_ == null) {
                    ensurePropertiesIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, properties_);
                    onChanged();
                } else {
                    propertiesBuilder_.addAllMessages(values);
                }
                return this;
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public Builder clearProperties() {
                if (propertiesBuilder_ == null) {
                    properties_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    propertiesBuilder_.clear();
                }
                return this;
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public Builder removeProperties(int index) {
                if (propertiesBuilder_ == null) {
                    ensurePropertiesIsMutable();
                    properties_.remove(index);
                    onChanged();
                } else {
                    propertiesBuilder_.remove(index);
                }
                return this;
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public ita.ms.PropertyOuterClass.Property.Builder getPropertiesBuilder(
                    int index) {
                return getPropertiesFieldBuilder().getBuilder(index);
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public ita.ms.PropertyOuterClass.PropertyOrBuilder getPropertiesOrBuilder(
                    int index) {
                if (propertiesBuilder_ == null) {
                    return properties_.get(index);  } else {
                    return propertiesBuilder_.getMessageOrBuilder(index);
                }
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public java.util.List<? extends ita.ms.PropertyOuterClass.PropertyOrBuilder>
            getPropertiesOrBuilderList() {
                if (propertiesBuilder_ != null) {
                    return propertiesBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(properties_);
                }
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public ita.ms.PropertyOuterClass.Property.Builder addPropertiesBuilder() {
                return getPropertiesFieldBuilder().addBuilder(
                        ita.ms.PropertyOuterClass.Property.getDefaultInstance());
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public ita.ms.PropertyOuterClass.Property.Builder addPropertiesBuilder(
                    int index) {
                return getPropertiesFieldBuilder().addBuilder(
                        index, ita.ms.PropertyOuterClass.Property.getDefaultInstance());
            }
            /**
             * <code>repeated .ita.ms.Property properties = 1;</code>
             */
            public java.util.List<ita.ms.PropertyOuterClass.Property.Builder>
            getPropertiesBuilderList() {
                return getPropertiesFieldBuilder().getBuilderList();
            }
            private com.google.protobuf.RepeatedFieldBuilderV3<
                    ita.ms.PropertyOuterClass.Property, ita.ms.PropertyOuterClass.Property.Builder, ita.ms.PropertyOuterClass.PropertyOrBuilder>
            getPropertiesFieldBuilder() {
                if (propertiesBuilder_ == null) {
                    propertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            ita.ms.PropertyOuterClass.Property, ita.ms.PropertyOuterClass.Property.Builder, ita.ms.PropertyOuterClass.PropertyOrBuilder>(
                            properties_,
                            ((bitField0_ & 0x00000001) != 0),
                            getParentForChildren(),
                            isClean());
                    properties_ = null;
                }
                return propertiesBuilder_;
            }
            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:ita.ms.PropertyList)
        }

        // @@protoc_insertion_point(class_scope:ita.ms.PropertyList)
        private static final ita.ms.PropertyOuterClass.PropertyList DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new ita.ms.PropertyOuterClass.PropertyList();
        }

        public static ita.ms.PropertyOuterClass.PropertyList getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<PropertyList>
                PARSER = new com.google.protobuf.AbstractParser<PropertyList>() {
            @java.lang.Override
            public PropertyList parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new PropertyList(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<PropertyList> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<PropertyList> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public ita.ms.PropertyOuterClass.PropertyList getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ita_ms_Property_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ita_ms_Property_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ita_ms_PropertyList_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ita_ms_PropertyList_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016property.proto\022\006ita.ms\"W\n\010Property\022\r\n\005" +
                        "title\030\001 \001(\t\022\020\n\010location\030\002 \001(\t\022\014\n\004link\030\003 " +
                        "\001(\t\022\r\n\005price\030\004 \001(\t\022\r\n\005image\030\005 \001(\t\"4\n\014Pro" +
                        "pertyList\022$\n\nproperties\030\001 \003(\0132\020.ita.ms.P" +
                        "roperty2I\n\017PropertyService\0226\n\006getAll\022\024.i" +
                        "ta.ms.PropertyList\032\024.ita.ms.PropertyList" +
                        "\"\000b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                                                new com.google.protobuf.Descriptors.FileDescriptor[] {
                                                });
        internal_static_ita_ms_Property_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ita_ms_Property_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ita_ms_Property_descriptor,
                new java.lang.String[] { "Title", "Location", "Link", "Price", "Image", });
        internal_static_ita_ms_PropertyList_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_ita_ms_PropertyList_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ita_ms_PropertyList_descriptor,
                new java.lang.String[] { "Properties", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}

