name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.1

      - name: Build and test
        run: mvn clean install --file ./backend/users/pom.xml
          
#      - name: Setup PostgreSQL
#        # You may pin to the exact commit or the version.
#        # uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
#        uses: Harmon758/postgresql-action@v1.0.0
#        with:
#          # Version of PostgreSQL to use
#          # POSTGRES_DB - name for the default database that is created
#          postgresql db: itausers
#          # POSTGRES_USER - create the specified user with superuser power
#          postgresql user: postgres
#          # POSTGRES_PASSWORD - superuser password
#          postgresql password: root

#      - name: Build with Maven
#        run: mvn -B package --file ./backend/users/pom.xml
#
#      - name: Test with Maven
#        run: mvn -B test --file ./backend/users/pom.xml
