name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Setup PostgreSQL
        uses: docker-compose@v2
        with:
          compose-file: ./docker-compose.yml
          services: db

      - name: Build with Maven
        run: mvn -B package --file ./backend/users/pom.xml

      - name: Test with Maven
        run: mvn -B test --file ./backend/users/pom.xml

