name: ci

on:
  push:
    branches:
      - main


jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: itausers
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Build and test
      run: mvn clean install --file ./backend/users/pom.xml


#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: 'temurin'
#
#
#      - name: Setup PostgreSQL
#        uses: Harmon758/postgresql-action@v1.0.0
#        with:
#          postgresql db: itausers
#          # POSTGRES_USER - create the specified user with superuser power
#          postgresql user: postgres
#          # POSTGRES_PASSWORD - superuser password
#          postgresql password: root
#
#      - name: Build and test
#        run: mvn clean install --file ./backend/users/pom.xml
#
#
#      - name: Build with Maven
#        run: mvn -B package --file ./backend/users/pom.xml
#
#      - name: Test with Maven
#        run: mvn -B test --file ./backend/users/pom.xml
