name: ci

on:
  push:
    branches:
      - main


jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
          POSTGRES_DB: itausers
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Build and test
      run: mvn clean install --file ./backend/users/pom.xml
    - uses: codecov/codecov-action@v3
      with:
        directory: ./backend/users/target/site/jacoco
        verbose: true

    - name: Archive code coverage results
    - uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./backend/users/target/site/jacoco

